pyroscope:
  config: |
    storage:
      backend: s3
      s3:
        endpoint: %ENDPOINT%
        bucket_name: %BUCKET%
        access_key_id: %USERNAME%
        secret_access_key: %PASSWORD%
        insecure: false
  # WEC configuration should set "insecure: false otherwise set to `true` for core"
  podSecurityContext:
    fsGroup: null
    runAsUser: null
    runAsNonRoot: null
  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # fsGroup: 1000800000
    # runAsUser: 1000800000
    # runAsNonRoot: true
